project:
  type: website
  output-dir: docs

website:
  title: "Swapnil Motghare"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - teaching.qmd

format:
  html:
    theme:
      light: yeti
      dark: slate
    css: styles.css
    toc: true

editor: visual

